### ISSUE TITLE
Unexpected token name «of», expected punc «;»

### ISSUE THREAD

**Issue by flyingmate** [sospartan/react-native-console-panel#1]
Hi,

I can build react-native-console-panel on genymotion,
but building with my android device(with option displayIgnoreDevVariable) is failed.
react-native device build(./android/gradlew installRelease) does not allow to use [for..of] syntax..

https://github.com/facebook/react-native/issues/1499

Can you change [for .. of] to forEach or [for .. in]?

Thank you

**Comment by sospartan** [comment]
Thank you . I will fix it in one minute.
