### ISSUE TITLE
Error: Naming collision detected:

### ISSUE THREAD

**Issue by flyingmate** [sospartan/react-native-console-panel#2]
Hi, I've got another error below. 
It works after deleting react-*\* folders under the react-native-console-panel/node_modules folder.
Dependency definition in console-panel's package.json file may cause this problem. 
Would you solve this? Some other react-native libraries have the same problem :(

Error: Naming collision detected: /Users/james/Dropbox/Development/react/Builder/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/Array.prototype.es6.js collides with /Users/james/Dropbox/Development/react/Builder/node_modules/react-native-console-panel/node_modules/react-native/packager/react-packager/src/DependencyResolver/polyfills/Array.prototype.es6.js

**Comment by sospartan** [comment]
I already fix this by remove the react-native dependency . Try the latest version.

**Comment by sospartan** [comment]
Is lateast version help ? @flyingmate

**Comment by flyingmate** [comment]
Sorry for the late response.

It's not generating duplicated react folders now, works perfectly. 
Thank you for the quick fix. 

P.S. I like the drag feature using PanResponder by the way.
