### ISSUE TITLE
Invalid prop 'color' supplied to 'Stylesheet warn': peachPuff

### ISSUE THREAD

**Issue by antoinechalifour** [sospartan/react-native-console-panel#3]
Hi there,

Just installed this module, and I ran into this issue "Invalid prop 'color' supplied to 'StyleSheet want': peachPuff". Here is the screenshot :
![screenshot_20160227-134220](https://cloud.githubusercontent.com/assets/6087868/13372898/78f0f678-dd58-11e5-9b52-dd52cb63f633.png)

Tried to run it on my Nexus 6 using react-native 0.20.0.

**Comment by vladp** [comment]
+1. Experiencing same issue
RN 0.22.2 , Android API 22 and 23

**Comment by sospartan** [comment]
fixed in fbdd32e
