### ISSUE TITLE
Can't find variable 'v'

### ISSUE THREAD

**Issue by jesseteal** [sospartan/react-native-console-panel#4]
I installed the module and added:

var ConsolePanel = require('react-native-console-panel').displayIgnoreDevVariable();

also tried

var ConsolePanel = require('react-native-console-panel'). displayWhenDev();

removing the line removes the error.

![simulator screen shot jun 15 2016 6 22 04 pm](https://cloud.githubusercontent.com/assets/1916717/16103646/be2b9b02-3326-11e6-93ab-5694c89a613a.png)

**Comment by jesseteal** [comment]
i fixed it, submitted a pull request

**Comment by sospartan** [comment]
Thanks a lot. I've merge your PR.

**Comment by inderps** [comment]
Then pls release a new version as well with the merged PR.

**Comment by sospartan** [comment]
@inderps sorry, my bad. I've fix this in v0.0.9 release.
